# Generated by Django 3.2.22 on 2023-10-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('opciones_respuesta', models.ManyToManyField(related_name='preguntas', to='CursosApp.OpcionRespuesta')),
                ('respuesta_correcta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.opcionrespuesta')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('descripcion', models.TextField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso')),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('preguntas', models.ManyToManyField(related_name='quizzes', to='CursosApp.Pregunta')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_entrega', models.DateField()),
                ('tipo_actividad', models.CharField(max_length=50)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='actividades/')),
                ('requisitos', models.TextField()),
                ('calificacion_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('enlace_externo', models.URLField(blank=True, null=True)),
                ('notas_instructor', models.TextField(blank=True, null=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso')),
            ],
        ),
    ]
